version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: spy_cats_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spy_cats_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./schema:/docker-entrypoint-initdb.d  # Автоматичне виконання міграцій
    networks:
      - spy_cats_network

  migrate:
    image: migrate/migrate
    container_name: spy_cats_migrate
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["migrate", "-path", "./schema", "-database", "postgres://admin:admin@postgres:5432/spy_cats_db?sslmode=disable", "up"]
    depends_on:
      - postgres
    networks:
      - spy_cats_network
    restart: "no"

  spy_cats_apps:
    build:
      context: .
      dockerfile: local.Dockerfile
    container_name: spy_cats_go_app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/spy_cats_db?sslmode=disable
    depends_on:
      - postgres
      - migrate
    networks:
      - spy_cats_network
    restart: always 
    ports:
      - "8080:8080"

networks:
  spy_cats_network:
    driver: bridge
